// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: '热门工具',
    tools: [
      {
        href: '/src/pages/pdf-multi-tool.html',
        name: 'PDF 多功能工具',
        icon: 'pencil-ruler',
        subtitle: '在统一界面中合并、拆分、整理、删除、旋转、添加空白页、提取和复制。',
      },
      {
        id: 'merge',
        name: '合并 PDF',
        icon: 'combine',
        subtitle: '将多个 PDF 合并为一个文件。',
      },
      {
        id: 'split',
        name: '拆分 PDF',
        icon: 'scissors',
        subtitle: '提取页面范围到新的 PDF。',
      },
      {
        id: 'compress',
        name: '压缩 PDF',
        icon: 'zap',
        subtitle: '减小 PDF 文件大小。',
      },
      {
        id: 'edit',
        name: 'PDF 编辑器',
        icon: 'pocket-knife',
        subtitle:
          '注释、高亮、涂黑、评论、添加形状/图片、搜索和查看 PDF',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG 转 PDF',
        icon: 'image-up',
        subtitle: '从一个或多个 JPG 图片创建 PDF。',
      },
      {
        id: 'sign-pdf',
        name: '签署 PDF',
        icon: 'pen-tool',
        subtitle: '绘制、输入或上传您的签名。',
      },
      {
        id: 'cropper',
        name: '裁剪 PDF',
        icon: 'crop',
        subtitle: '修剪 PDF 中每一页的边距。',
      },
      {
        id: 'extract-pages',
        name: '提取页面',
        icon: 'ungroup',
        subtitle: '将选定的页面保存为新文件。',
      },
      {
        id: 'duplicate-organize',
        name: '复制和整理',
        icon: 'files',
        subtitle: '复制、重新排序和删除页面。',
      },
      {
        id: 'delete-pages',
        name: '删除页面',
        icon: 'trash-2',
        subtitle: '从文档中删除特定页面。',
      },
    ],
  },
  {
    name: '编辑和注释',
    tools: [
      {
        id: 'edit',
        name: 'PDF 编辑器',
        icon: 'pocket-knife',
        subtitle:
          '注释、高亮、涂黑、评论、添加形状/图片、搜索和查看 PDF。',
      },
      {
        // id: 'bookmark-pdf',
        href: '/src/pages/bookmark.html',
        name: '编辑书签',
        icon: 'bookmark',
        subtitle: '添加、编辑、导入、删除和提取 PDF 书签。',
      },
      {
        href: '/src/pages/table-of-contents.html',
        name: '目录',
        icon: 'list',
        subtitle: '从 PDF 书签生成目录页。',
      },
      {
        id: 'add-page-numbers',
        name: '页码',
        icon: 'list-ordered',
        subtitle: '在文档中插入页码。',
      },
      {
        id: 'add-watermark',
        name: '添加水印',
        icon: 'droplets',
        subtitle: '在 PDF 页面上加盖文本或图片。',
      },
      {
        id: 'add-header-footer',
        name: '页眉和页脚',
        icon: 'pilcrow',
        subtitle: '在页面顶部和底部添加文本。',
      },
      {
        id: 'invert-colors',
        name: '反转颜色',
        icon: 'contrast',
        subtitle: '创建 PDF 的"暗色模式"版本。',
      },
      {
        id: 'change-background-color',
        name: '背景颜色',
        icon: 'palette',
        subtitle: '更改 PDF 的背景颜色。',
      },
      {
        id: 'change-text-color',
        name: '更改文本颜色',
        icon: 'type',
        subtitle: '更改 PDF 中文本的颜色。',
      },
      {
        id: 'sign-pdf',
        name: '签署 PDF',
        icon: 'pen-tool',
        subtitle: '绘制、输入或上传您的签名。',
      },
      {
        href: '/src/pages/add-stamps.html',
        name: '添加印章',
        icon: 'stamp',
        subtitle: '使用注释工具栏向 PDF 添加图片印章。',
      },
      {
        id: 'remove-annotations',
        name: '删除注释',
        icon: 'eraser',
        subtitle: '删除评论、高亮和链接。',
      },
      {
        id: 'cropper',
        name: '裁剪 PDF',
        icon: 'crop',
        subtitle: '修剪 PDF 中每一页的边距。',
      },
      {
        id: 'form-filler',
        name: 'PDF 表单填写',
        icon: 'square-pen',
        subtitle: '直接在浏览器中填写表单。也支持 XFA 表单。',
      },
      {
        href: '/src/pages/form-creator.html',
        name: '创建 PDF 表单',
        icon: 'file-input',
        subtitle: '使用拖放文本字段创建可填写的 PDF 表单。',
      },
      {
        id: 'remove-blank-pages',
        name: '删除空白页',
        icon: 'file-minus-2',
        subtitle: '自动检测并删除空白页。',
      },
    ],
  },
  {
    name: '转换为 PDF',
    tools: [
      {
        id: 'image-to-pdf',
        name: '图片转 PDF',
        icon: 'images',
        subtitle: '将 JPG、PNG、WebP、BMP、TIFF、SVG、HEIC 转换为 PDF。',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG 转 PDF',
        icon: 'image-up',
        subtitle: '从一个或多个 JPG 图片创建 PDF。',
      },
      {
        id: 'png-to-pdf',
        name: 'PNG 转 PDF',
        icon: 'image-up',
        subtitle: '从一个或多个 PNG 图片创建 PDF。',
      },
      {
        id: 'webp-to-pdf',
        name: 'WebP 转 PDF',
        icon: 'image-up',
        subtitle: '从一个或多个 WebP 图片创建 PDF。',
      },
      {
        id: 'svg-to-pdf',
        name: 'SVG 转 PDF',
        icon: 'pen-tool',
        subtitle: '从一个或多个 SVG 图片创建 PDF。',
      },
      {
        id: 'bmp-to-pdf',
        name: 'BMP 转 PDF',
        icon: 'image',
        subtitle: '从一个或多个 BMP 图片创建 PDF。',
      },
      {
        id: 'heic-to-pdf',
        name: 'HEIC 转 PDF',
        icon: 'smartphone',
        subtitle: '从一个或多个 HEIC 图片创建 PDF。',
      },
      {
        id: 'tiff-to-pdf',
        name: 'TIFF 转 PDF',
        icon: 'layers',
        subtitle: '从一个或多个 TIFF 图片创建 PDF。',
      },
      {
        id: 'txt-to-pdf',
        name: '文本转 PDF',
        icon: 'file-pen',
        subtitle: '将纯文本文件转换为 PDF。',
      },
      {
        href: '/src/pages/json-to-pdf.html',
        name: 'JSON 转 PDF',
        icon: 'file-code',
        subtitle: '将 JSON 文件转换为 PDF 格式。',
      },
      // { id: 'md-to-pdf', name: 'Markdown to PDF', icon: 'file-text', subtitle: 'Convert a Markdown file into a PDF.' },
      // { id: 'scan-to-pdf', name: 'Scan to PDF', icon: 'camera', subtitle: 'Use your camera to create a scanned PDF.' },
      // { id: 'word-to-pdf', name: 'Word to PDF', icon: 'file-text', subtitle: 'Convert .docx documents to PDF.' },
    ],
  },
  {
    name: '从 PDF 转换',
    tools: [
      {
        id: 'pdf-to-jpg',
        name: 'PDF 转 JPG',
        icon: 'file-image',
        subtitle: '将每个 PDF 页面转换为 JPG 图片。',
      },
      {
        id: 'pdf-to-png',
        name: 'PDF 转 PNG',
        icon: 'file-image',
        subtitle: '将每个 PDF 页面转换为 PNG 图片。',
      },
      {
        id: 'pdf-to-webp',
        name: 'PDF 转 WebP',
        icon: 'file-image',
        subtitle: '将每个 PDF 页面转换为 WebP 图片。',
      },
      {
        id: 'pdf-to-bmp',
        name: 'PDF 转 BMP',
        icon: 'file-image',
        subtitle: '将每个 PDF 页面转换为 BMP 图片。',
      },
      {
        id: 'pdf-to-tiff',
        name: 'PDF 转 TIFF',
        icon: 'file-image',
        subtitle: '将每个 PDF 页面转换为 TIFF 图片。',
      },
      {
        id: 'pdf-to-greyscale',
        name: 'PDF 转灰度',
        icon: 'palette',
        subtitle: '将所有颜色转换为黑白。',
      },
      {
        href: '/src/pages/pdf-to-json.html',
        name: 'PDF 转 JSON',
        icon: 'file-code',
        subtitle: '将 PDF 文件转换为 JSON 格式。',
      },
      // { id: 'pdf-to-markdown', name: 'PDF to Markdown', icon: 'file-pen', subtitle: 'Extract text into a Markdown file.' },
    ],
  },
  {
    name: '整理和管理',
    tools: [
      {
        id: 'ocr-pdf',
        name: 'OCR PDF',
        icon: 'scan-text',
        subtitle: '使 PDF 可搜索和可复制。',
      },
      {
        id: 'merge',
        name: '合并 PDF',
        icon: 'combine',
        subtitle: '将多个 PDF 合并为一个文件。',
      },
      {
        id: 'alternate-merge',
        name: '交替和混合页面',
        icon: 'shuffle',
        subtitle: '通过交替每个 PDF 的页面来合并 PDF。',
      },
      {
        id: 'organize',
        name: '整理 PDF',
        icon: 'grip',
        subtitle: '通过拖放重新排序页面。',
      },
      {
        id: 'duplicate-organize',
        name: '复制和整理',
        icon: 'files',
        subtitle: '复制、重新排序和删除页面。',
      },
      {
        id: 'add-attachments',
        name: '添加附件',
        icon: 'paperclip',
        subtitle: '将一个或多个文件嵌入到 PDF 中。',
      },
      {
        id: 'extract-attachments',
        name: '提取附件',
        icon: 'download',
        subtitle: '从 PDF 中提取所有嵌入文件为 ZIP。',
      },
      {
        id: 'edit-attachments',
        name: '编辑附件',
        icon: 'file-edit',
        subtitle: '查看或删除 PDF 中的附件。',
      },
      {
        href: '/src/pages/pdf-multi-tool.html',
        name: 'PDF 多功能工具',
        icon: 'pencil-ruler',
        subtitle: '具有页面管理功能的全功能 PDF 编辑器。',
      },
      {
        id: 'split',
        name: '拆分 PDF',
        icon: 'scissors',
        subtitle: '提取页面范围到新的 PDF。',
      },
      {
        id: 'split-in-half',
        name: '分割页面',
        icon: 'table-columns-split',
        subtitle: '水平或垂直分割页面。',
      },
      {
        id: 'extract-pages',
        name: '提取页面',
        icon: 'ungroup',
        subtitle: '将选定的页面保存为新文件。',
      },
      {
        id: 'delete-pages',
        name: '删除页面',
        icon: 'trash-2',
        subtitle: '从文档中删除特定页面。',
      },
      {
        id: 'add-blank-page',
        name: '添加空白页',
        icon: 'file-plus-2',
        subtitle: '在 PDF 的任意位置插入空白页。',
      },
      {
        id: 'reverse-pages',
        name: '反转页面',
        icon: 'arrow-down-z-a',
        subtitle: '翻转文档中所有页面的顺序。',
      },
      {
        id: 'rotate',
        name: '旋转 PDF',
        icon: 'rotate-cw',
        subtitle: '以 90 度增量旋转页面。',
      },
      {
        id: 'n-up',
        name: 'N 合一 PDF',
        icon: 'layout-grid',
        subtitle: '将多个页面排列到单张纸上。',
      },
      {
        id: 'combine-single-page',
        name: '合并为单页',
        icon: 'unfold-vertical',
        subtitle: '将所有页面拼接成一个连续滚动页面。',
      },
      {
        id: 'view-metadata',
        name: '查看元数据',
        icon: 'info',
        subtitle: '检查 PDF 的隐藏属性。',
      },
      {
        id: 'edit-metadata',
        name: '编辑元数据',
        icon: 'file-cog',
        subtitle: '更改作者、标题和其他属性。',
      },
      {
        id: 'pdf-to-zip',
        name: 'PDF 转 ZIP',
        icon: 'stretch-horizontal',
        subtitle: '将多个 PDF 文件打包成 ZIP 压缩包。',
      },
      {
        id: 'compare-pdfs',
        name: '比较 PDF',
        icon: 'git-compare',
        subtitle: '并排比较两个 PDF。',
      },
      {
        id: 'posterize',
        name: '海报化 PDF',
        icon: 'notepad-text-dashed',
        subtitle: '将大页面拆分为多个较小的页面。',
      },
    ],
  },
  {
    name: '优化和修复',
    tools: [
      {
        id: 'compress',
        name: '压缩 PDF',
        icon: 'zap',
        subtitle: '减小 PDF 文件大小。',
      },
      {
        id: 'fix-dimensions',
        name: '修复页面大小',
        icon: 'ruler-dimension-line',
        subtitle: '将所有页面标准化为统一大小。',
      },
      {
        id: 'linearize',
        name: '线性化 PDF',
        icon: 'gauge',
        subtitle: '优化 PDF 以实现快速网络查看。',
      },
      {
        id: 'page-dimensions',
        name: '页面尺寸',
        icon: 'ruler',
        subtitle: '分析页面大小、方向和单位。',
      },
      {
        id: 'remove-restrictions',
        name: '移除限制',
        icon: 'unlink',
        subtitle:
          '移除与数字签名 PDF 文件相关的密码保护和安全限制。',
      },
    ],
  },
  {
    name: '保护 PDF',
    tools: [
      {
        id: 'encrypt',
        name: '加密 PDF',
        icon: 'lock',
        subtitle: '通过添加密码锁定 PDF。',
      },
      {
        id: 'sanitize-pdf',
        name: '清理 PDF',
        icon: 'brush-cleaning',
        subtitle: '删除元数据、注释、脚本等。',
      },
      {
        id: 'decrypt',
        name: '解密 PDF',
        icon: 'unlock',
        subtitle: '通过移除密码保护来解锁 PDF。',
      },
      {
        id: 'flatten',
        name: '扁平化 PDF',
        icon: 'layers',
        subtitle: '使表单字段和注释不可编辑。',
      },
      {
        id: 'remove-metadata',
        name: '删除元数据',
        icon: 'file-x',
        subtitle: '从 PDF 中删除隐藏数据。',
      },
      {
        id: 'change-permissions',
        name: '更改权限',
        icon: 'shield-check',
        subtitle: '设置或更改 PDF 的用户权限。',
      },
    ],
  },
];
